### ISSUE TITLE
Adding Ecobee to HomeKit crashes the Homebridge server

### ISSUE THREAD

**Issue by Chiragbrains** [vojtamolda/homebridge-ecobee3-sensors#22]
```
[11/7/2017, 9:11:45 PM] Loaded plugin: homebridge-ecobee3-sensors
Homebridge API version: 2.2
[11/7/2017, 9:11:45 PM] Registering platform 'homebridge-ecobee3-sensors.Ecobee 3 Sensors'
[11/7/2017, 9:11:45 PM] ---
[11/7/2017, 9:11:45 PM] Loaded config.json with 0 accessories and 1 platforms.
[11/7/2017, 9:11:45 PM] ---
[11/7/2017, 9:11:45 PM] Loading 1 platforms...
[11/7/2017, 9:11:45 PM] [Ecobee] Initializing Ecobee 3 Sensors platform...
[11/7/2017, 9:11:45 PM] Loading 0 accessories...
[11/7/2017, 9:11:45 PM] Homebridge is running on port 51826.
[11/7/2017, 9:11:46 PM] [Ecobee] These are the steps authorize this application to access your Ecobee 3:
[11/7/2017, 9:11:46 PM] [Ecobee]   1. Go to https://www.ecobee.com/home/ecobeeLogin.jsp
[11/7/2017, 9:11:46 PM] [Ecobee]   2. Login to your thermostat console 
[11/7/2017, 9:11:46 PM] [Ecobee]   3. Select 'MY APPS' from the menu on the top right.
[11/7/2017, 9:11:46 PM] [Ecobee]   4. Click 'Add Application' 
[11/7/2017, 9:11:46 PM] [Ecobee]   5. Enter the following authorization code:
[11/7/2017, 9:11:46 PM] [Ecobee]    ┌──────┐  
[11/7/2017, 9:11:46 PM] [Ecobee]    │ e9xw │  
[11/7/2017, 9:11:46 PM] [Ecobee]    └──────┘  
[11/7/2017, 9:11:46 PM] [Ecobee]   6. Wait a moment.
[11/7/2017, 9:11:46 PM] [Ecobee] Waiting for user to authorize application. Retrying in 30 seconds.
[11/7/2017, 9:12:17 PM] [Ecobee] Authorization successful :-)
[11/7/2017, 9:12:17 PM] [Ecobee] Update sensors
[11/7/2017, 9:12:17 PM] [Ecobee] Create | Family Room | ZF32
[11/7/2017, 9:12:17 PM] [Ecobee] [Family Room] Initialized | ZF32
[11/7/2017, 9:12:17 PM] [Ecobee] [Family Room] Occupied
[11/7/2017, 9:12:17 PM] [Ecobee] Wait | 30 seconds
[11/7/2017, 9:12:18 PM] [Ecobee] Tokens
[11/7/2017, 9:12:49 PM] [Ecobee] Update sensors
[11/7/2017, 9:12:49 PM] [Ecobee] [Family Room] Occupied
[11/7/2017, 9:12:49 PM] [Ecobee] Wait | 30 seconds
[11/7/2017, 9:13:20 PM] [Ecobee] Update sensors
[11/7/2017, 9:13:20 PM] [Ecobee] [Family Room] Occupied
[11/7/2017, 9:13:20 PM] [Ecobee] Wait | 30 seconds
[11/7/2017, 9:13:21 PM] [Ecobee] [Family Room] Identify
/usr/local/lib/node_modules/homebridge-ecobee3-sensors/source/sensor.js:116
  callback();
  ^

TypeError: callback is not a function
    at EcobeeSensor.identify (/usr/local/lib/node_modules/homebridge-ecobee3-sensors/source/sensor.js:116:3)
    at emitTwo (events.js:106:13)
    at PlatformAccessory.emit (events.js:191:7)
    at PlatformAccessory.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/platformAccessory.js:155:12)
    at emitTwo (events.js:106:13)
    at Accessory.emit (events.js:191:7)
    at Accessory._identificationRequest (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:122:10)
    at Accessory.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:984:14)
    at emitMany (events.js:127:13)
    at emit (events.js:201:7)
```

**Comment by vojtamolda** [comment]
Hello @Chiragbrains,

Thanks for opening the issue here and I apologize for your problems. I'll try to fix it as soon as possible. At the moment I'm having trouble reproducing the crash and the issue seems serious enough to be easily overlooked in any earlier release.

Can you, please, try to run _Homebridge_ server in debug mode (`homebridge -D`) and re-post the log here? Also what plugin version and _Homebridge_ version are you using?

**Comment by Chiragbrains** [comment]
This is what I see when I do `homebridge -D`
As soon as I add the homebridge to HomeKit, it crashes saying:
```
/usr/local/lib/node_modules/homebridge-ecobee3-sensors/source/sensor.js:116
  callback();
  ^

TypeError: callback is not a function
    at EcobeeSensor.identify (/usr/local/lib/node_modules/homebridge-ecobee3-sensors/source/sensor.js:116:3)
    at emitTwo (events.js:106:13)
    at PlatformAccessory.emit (events.js:191:7)
    at PlatformAccessory.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/platformAccessory.js:155:12)
    at emitTwo (events.js:106:13)
    at Accessory.emit (events.js:191:7)
    at Accessory._identificationRequest (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:122:10)
    at Accessory.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:984:14)
    at emitMany (events.js:127:13)
    at Characteristic.emit (events.js:201:7)
```

<details>
<summary>Homebridge Debug Log</summary>

```
XX-MBP:~ chirag$ homebridge -D
[11/8/2017, 6:45:59 PM] Loaded plugin: homebridge-ecobee3-sensors
Homebridge API version: 2.2
[11/8/2017, 6:45:59 PM] Registering platform 'homebridge-ecobee3-sensors.Ecobee 3 Sensors'
[11/8/2017, 6:45:59 PM] ---
[11/8/2017, 6:45:59 PM] Loaded config.json with 0 accessories and 1 platforms.
[11/8/2017, 6:45:59 PM] ---
[11/8/2017, 6:45:59 PM] Loading 1 platforms...
[11/8/2017, 6:45:59 PM] [Ecobee] Initializing Ecobee 3 Sensors platform...
[11/8/2017, 6:45:59 PM] Loading 0 accessories...
Scan this code with your HomeKit app on your iOS device to pair with Homebridge
[11/8/2017, 6:45:59 PM] [Ecobee] Finished launching...
[11/8/2017, 6:45:59 PM] [Ecobee] Requesting authorization code...
[11/8/2017, 6:45:59 PM] Homebridge is running on port 51826.
[11/8/2017, 6:46:00 PM] [Ecobee] { ecobeePin: 'e8fu',
  code: 'd06l2mzQidSjhrhcoJAisOPko9teoqpO',
  scope: 'smartRead',
  expires_in: 9,
  interval: 30 }
[11/8/2017, 6:46:00 PM] [Ecobee] These are the steps authorize this application to access your Ecobee 3:
[11/8/2017, 6:46:00 PM] [Ecobee]   1. Go to https://www.ecobee.com/home/ecobeeLogin.jsp
[11/8/2017, 6:46:00 PM] [Ecobee]   2. Login to your thermostat console 
[11/8/2017, 6:46:00 PM] [Ecobee]   3. Select 'MY APPS' from the menu on the top right.
[11/8/2017, 6:46:00 PM] [Ecobee]   4. Click 'Add Application' 
[11/8/2017, 6:46:00 PM] [Ecobee]   5. Enter the following authorization code:
[11/8/2017, 6:46:00 PM] [Ecobee]    ┌──────┐  
[11/8/2017, 6:46:00 PM] [Ecobee]    │ e8fu │  
[11/8/2017, 6:46:00 PM] [Ecobee]    └──────┘  
[11/8/2017, 6:46:00 PM] [Ecobee]   6. Wait a moment.
[11/8/2017, 6:46:00 PM] [Ecobee] Authorizing plugin to access the thermostat...
[11/8/2017, 6:46:00 PM] [Ecobee] ClientRequest {
  domain: null,
  _events: 
   { response: { [Function: g] listener: [Function: bound ] },
     socket: { [Function: g] listener: [Function: onSocket] },
     error: [Function: bound ] },
  _eventsCount: 3,
  _maxListeners: undefined,
  output: [ 'POST /token HTTP/1.1\r\ncontent-type: application/x-www-form-urlencoded\r\nHost: api.ecobee.com\r\nConnection: close\r\nTransfer-Encoding: chunked\r\n\r\n65\r\ngrant_type=ecobeePin&client_id=DALCINnO49EYOmMfQQxmx7PYofM1YEGo&code=d06l2mzQidSjhrhcoJAisOPko9teoqpO\r\n' ],
  outputEncodings: [ undefined ],
  outputCallbacks: [ undefined ],
  outputSize: 249,
  writable: true,
  _last: true,
  upgrading: false,
  chunkedEncoding: true,
  shouldKeepAlive: false,
  useChunkedEncodingByDefault: true,
  sendDate: false,
  _removedHeader: {},
  _contentLength: null,
  _hasBody: true,
  _trailer: '',
  finished: false,
  _headerSent: true,
  socket: null,
  connection: null,
  _header: 'POST /token HTTP/1.1\r\ncontent-type: application/x-www-form-urlencoded\r\nHost: api.ecobee.com\r\nConnection: close\r\nTransfer-Encoding: chunked\r\n\r\n',
  _headers: 
   { 'content-type': 'application/x-www-form-urlencoded',
     host: 'api.ecobee.com' },
  _headerNames: { 'content-type': 'content-type', host: 'Host' },
  _onPendingData: null,
  agent: 
   Agent {
     domain: null,
     _events: { free: [Function] },
     _eventsCount: 1,
     _maxListeners: undefined,
     defaultPort: 443,
     protocol: 'https:',
     options: { path: null },
     requests: {},
     sockets: { 'api.ecobee.com:443::::::::': [Object] },
     freeSockets: {},
     keepAliveMsecs: 1000,
     keepAlive: false,
     maxSockets: Infinity,
     maxFreeSockets: 256,
     maxCachedSessions: 100,
     _sessionCache: { map: [Object], list: [Object] } },
  socketPath: undefined,
  timeout: undefined,
  method: 'POST',
  path: '/token',
  _ended: false }
[11/8/2017, 6:46:00 PM] [Ecobee] { error: 'authorization_pending',
  error_description: 'Waiting for user to authorize application.',
  error_uri: 'https://tools.ietf.org/html/rfc6749#section-5.2' }
[11/8/2017, 6:46:00 PM] [Ecobee] Waiting for user to authorize application. Retrying in 30 seconds.
[11/8/2017, 6:46:31 PM] [Ecobee] Authorizing plugin to access the thermostat...
[11/8/2017, 6:46:31 PM] [Ecobee] ClientRequest {
  domain: null,
  _events: 
   { response: { [Function: g] listener: [Function: bound ] },
     socket: { [Function: g] listener: [Function: onSocket] },
     error: [Function: bound ] },
  _eventsCount: 3,
  _maxListeners: undefined,
  output: [ 'POST /token HTTP/1.1\r\ncontent-type: application/x-www-form-urlencoded\r\nHost: api.ecobee.com\r\nConnection: close\r\nTransfer-Encoding: chunked\r\n\r\n65\r\ngrant_type=ecobeePin&client_id=DALCINnO49EYOmMfQQxmx7PYofM1YEGo&code=d06l2mzQidSjhrhcoJAisOPko9teoqpO\r\n' ],
  outputEncodings: [ undefined ],
  outputCallbacks: [ undefined ],
  outputSize: 249,
  writable: true,
  _last: true,
  upgrading: false,
  chunkedEncoding: true,
  shouldKeepAlive: false,
  useChunkedEncodingByDefault: true,
  sendDate: false,
  _removedHeader: {},
  _contentLength: null,
  _hasBody: true,
  _trailer: '',
  finished: false,
  _headerSent: true,
  socket: null,
  connection: null,
  _header: 'POST /token HTTP/1.1\r\ncontent-type: application/x-www-form-urlencoded\r\nHost: api.ecobee.com\r\nConnection: close\r\nTransfer-Encoding: chunked\r\n\r\n',
  _headers: 
   { 'content-type': 'application/x-www-form-urlencoded',
     host: 'api.ecobee.com' },
  _headerNames: { 'content-type': 'content-type', host: 'Host' },
  _onPendingData: null,
  agent: 
   Agent {
     domain: null,
     _events: { free: [Function] },
     _eventsCount: 1,
     _maxListeners: undefined,
     defaultPort: 443,
     protocol: 'https:',
     options: { path: null },
     requests: {},
     sockets: { 'api.ecobee.com:443::::::::': [Object] },
     freeSockets: {},
     keepAliveMsecs: 1000,
     keepAlive: false,
     maxSockets: Infinity,
     maxFreeSockets: 256,
     maxCachedSessions: 100,
     _sessionCache: { map: [Object], list: [Object] } },
  socketPath: undefined,
  timeout: undefined,
  method: 'POST',
  path: '/token',
  _ended: false }
[11/8/2017, 6:46:31 PM] [Ecobee] { access_token: 'AvPVoN94cvkqljm6bDr1HqMg7zQcFyGo',
  token_type: 'Bearer',
  expires_in: 3599,
  refresh_token: 'YdxT6cVjttzB3keTKYXwLFMStIDeJk0g',
  scope: 'smartRead' }
[11/8/2017, 6:46:31 PM] [Ecobee] Authorization successful :-)
[11/8/2017, 6:46:31 PM] [Ecobee] Updating sensors with fresh data...
[11/8/2017, 6:46:31 PM] [Ecobee] ClientRequest {
  domain: null,
  _events: 
   { response: { [Function: g] listener: [Function: bound ] },
     socket: { [Function: g] listener: [Function: onSocket] },
     error: [Function: bound ] },
  _eventsCount: 3,
  _maxListeners: undefined,
  output: [],
  outputEncodings: [],
  outputCallbacks: [],
  outputSize: 0,
  writable: true,
  _last: true,
  upgrading: false,
  chunkedEncoding: false,
  shouldKeepAlive: false,
  useChunkedEncodingByDefault: false,
  sendDate: false,
  _removedHeader: {},
  _contentLength: null,
  _hasBody: true,
  _trailer: '',
  finished: false,
  _headerSent: false,
  socket: null,
  connection: null,
  _header: null,
  _headers: 
   { 'content-type': 'application/json',
     authorization: 'Bearer AvPVoN94cvkqljm6bDr1HqMg7zQcFyGo',
     host: 'api.ecobee.com' },
  _headerNames: 
   { 'content-type': 'Content-Type',
     authorization: 'authorization',
     host: 'Host' },
  _onPendingData: null,
  agent: 
   Agent {
     domain: null,
     _events: { free: [Function] },
     _eventsCount: 1,
     _maxListeners: undefined,
     defaultPort: 443,
     protocol: 'https:',
     options: { path: null },
     requests: {},
     sockets: { 'api.ecobee.com:443::::::::': [Object] },
     freeSockets: {},
     keepAliveMsecs: 1000,
     keepAlive: false,
     maxSockets: Infinity,
     maxFreeSockets: 256,
     maxCachedSessions: 100,
     _sessionCache: { map: [Object], list: [Object] } },
  socketPath: undefined,
  timeout: undefined,
  method: 'GET',
  path: '/1/thermostat?json=%7B%22selection%22%3A%7B%22selectionType%22%3A%22registered%22%2C%22selectionMatch%22%3A%22%22%2C%22includeSensors%22%3Atrue%7D%7D',
  _ended: false }
[11/8/2017, 6:46:31 PM] [Ecobee] { page: { page: 1, totalPages: 1, pageSize: 1, total: 1 },
  thermostatList: 
   [ { identifier: '511856934572',
       name: 'C Ecobee',
       thermostatRev: '171108232231',
       isRegistered: true,
       modelNumber: 'apolloSmart',
       brand: 'ecobee',
       features: 'HomeKit',
       lastModified: '2017-11-08 23:22:31',
       thermostatTime: '2017-11-08 18:46:31',
       utcTime: '2017-11-08 23:46:31',
       remoteSensors: [Object] } ],
  status: { code: 0, message: '' } }
[11/8/2017, 6:46:31 PM] [Ecobee] Update sensors
[11/8/2017, 6:46:31 PM] [Ecobee] Setting values of sensors...
[11/8/2017, 6:46:31 PM] [Ecobee] Create | Family Room | ZF32
[11/8/2017, 6:46:31 PM] [Ecobee] [Family Room] Initializing sensor...
[11/8/2017, 6:46:31 PM] [Ecobee] { id: 'rs:100',
  name: 'Family Room',
  type: 'ecobee3_remote_sensor',
  code: 'ZF32',
  inUse: true,
  capability: 
   [ { id: '1', type: 'temperature', value: '716' },
     { id: '2', type: 'occupancy', value: 'true' } ] }
[11/8/2017, 6:46:31 PM] [Ecobee] [Family Room] Initialized | ZF32
[11/8/2017, 6:46:31 PM] [Ecobee] [Family Room] Updating sensor measurement...
[11/8/2017, 6:46:31 PM] [Ecobee] { id: 'rs:100',
  name: 'Family Room',
  type: 'ecobee3_remote_sensor',
  code: 'ZF32',
  inUse: true,
  capability: 
   [ { id: '1', type: 'temperature', value: '716' },
     { id: '2', type: 'occupancy', value: 'true' } ] }
[11/8/2017, 6:46:31 PM] [Ecobee] [Family Room] 22.0°C | Occupied
[11/8/2017, 6:46:31 PM] [Ecobee] Create | C Ecobee | 511856934572
[11/8/2017, 6:46:31 PM] [Ecobee] [C Ecobee] Initializing sensor...
[11/8/2017, 6:46:31 PM] [Ecobee] { id: 'ei:0',
  name: 'C Ecobee',
  type: 'thermostat',
  inUse: false,
  capability: 
   [ { id: '1', type: 'temperature', value: '721' },
     { id: '2', type: 'humidity', value: '57' },
     { id: '3', type: 'occupancy', value: 'true' } ],
  code: '511856934572' }
[11/8/2017, 6:46:31 PM] [Ecobee] [C Ecobee] Initialized | 511856934572
[11/8/2017, 6:46:31 PM] [Ecobee] [C Ecobee] Updating sensor measurement...
[11/8/2017, 6:46:31 PM] [Ecobee] { id: 'ei:0',
  name: 'C Ecobee',
  type: 'thermostat',
  inUse: false,
  capability: 
   [ { id: '1', type: 'temperature', value: '721' },
     { id: '2', type: 'humidity', value: '57' },
     { id: '3', type: 'occupancy', value: 'true' } ],
  code: '511856934572' }
[11/8/2017, 6:46:31 PM] [Ecobee] [C Ecobee] 22.3°C | 57% | Occupied
[11/8/2017, 6:46:31 PM] [Ecobee] Cleaning unused cached Homebridge accessories...
[11/8/2017, 6:46:31 PM] [Ecobee] {}
[11/8/2017, 6:46:31 PM] [Ecobee] Wait | 30 seconds
[11/8/2017, 6:46:31 PM] [Ecobee] Refreshing tokens...
[11/8/2017, 6:46:31 PM] [Ecobee] ClientRequest {
  domain: null,
  _events: 
   { response: { [Function: g] listener: [Function: bound ] },
     socket: { [Function: g] listener: [Function: onSocket] },
     error: [Function: bound ] },
  _eventsCount: 3,
  _maxListeners: undefined,
  output: [ 'POST /token HTTP/1.1\r\ncontent-type: application/x-www-form-urlencoded\r\nHost: api.ecobee.com\r\nConnection: close\r\nTransfer-Encoding: chunked\r\n\r\n69\r\ngrant_type=refresh_token&code=YdxT6cVjttzB3keTKYXwLFMStIDeJk0g&client_id=DALCINnO49EYOmMfQQxmx7PYofM1YEGo\r\n' ],
  outputEncodings: [ undefined ],
  outputCallbacks: [ undefined ],
  outputSize: 253,
  writable: true,
  _last: true,
  upgrading: false,
  chunkedEncoding: true,
  shouldKeepAlive: false,
  useChunkedEncodingByDefault: true,
  sendDate: false,
  _removedHeader: {},
  _contentLength: null,
  _hasBody: true,
  _trailer: '',
  finished: false,
  _headerSent: true,
  socket: null,
  connection: null,
  _header: 'POST /token HTTP/1.1\r\ncontent-type: application/x-www-form-urlencoded\r\nHost: api.ecobee.com\r\nConnection: close\r\nTransfer-Encoding: chunked\r\n\r\n',
  _headers: 
   { 'content-type': 'application/x-www-form-urlencoded',
     host: 'api.ecobee.com' },
  _headerNames: { 'content-type': 'content-type', host: 'Host' },
  _onPendingData: null,
  agent: 
   Agent {
     domain: null,
     _events: { free: [Function] },
     _eventsCount: 1,
     _maxListeners: undefined,
     defaultPort: 443,
     protocol: 'https:',
     options: { path: null },
     requests: {},
     sockets: { 'api.ecobee.com:443::::::::': [Object] },
     freeSockets: {},
     keepAliveMsecs: 1000,
     keepAlive: false,
     maxSockets: Infinity,
     maxFreeSockets: 256,
     maxCachedSessions: 100,
     _sessionCache: { map: [Object], list: [Object] } },
  socketPath: undefined,
  timeout: undefined,
  method: 'POST',
  path: '/token',
  _ended: false }
[11/8/2017, 6:46:32 PM] [Ecobee] { access_token: 'fXE5KiSnvdPkk66Wi0Uo9RQJCL6YB7Ff',
  token_type: 'Bearer',
  expires_in: 3599,
  refresh_token: '0JwmFA5geHMjoAA5iJK0yvOK8KYuaSYb',
  scope: 'smartRead' }
[11/8/2017, 6:46:32 PM] [Ecobee] Tokens
[11/8/2017, 6:47:02 PM] [Ecobee] Updating sensors with fresh data...
[11/8/2017, 6:47:02 PM] [Ecobee] ClientRequest {
  domain: null,
  _events: 
   { response: { [Function: g] listener: [Function: bound ] },
     socket: { [Function: g] listener: [Function: onSocket] },
     error: [Function: bound ] },
  _eventsCount: 3,
  _maxListeners: undefined,
  output: [],
  outputEncodings: [],
  outputCallbacks: [],
  outputSize: 0,
  writable: true,
  _last: true,
  upgrading: false,
  chunkedEncoding: false,
  shouldKeepAlive: false,
  useChunkedEncodingByDefault: false,
  sendDate: false,
  _removedHeader: {},
  _contentLength: null,
  _hasBody: true,
  _trailer: '',
  finished: false,
  _headerSent: false,
  socket: null,
  connection: null,
  _header: null,
  _headers: 
   { 'content-type': 'application/json',
     authorization: 'Bearer fXE5KiSnvdPkk66Wi0Uo9RQJCL6YB7Ff',
     host: 'api.ecobee.com' },
  _headerNames: 
   { 'content-type': 'Content-Type',
     authorization: 'authorization',
     host: 'Host' },
  _onPendingData: null,
  agent: 
   Agent {
     domain: null,
     _events: { free: [Function] },
     _eventsCount: 1,
     _maxListeners: undefined,
     defaultPort: 443,
     protocol: 'https:',
     options: { path: null },
     requests: {},
     sockets: { 'api.ecobee.com:443::::::::': [Object] },
     freeSockets: {},
     keepAliveMsecs: 1000,
     keepAlive: false,
     maxSockets: Infinity,
     maxFreeSockets: 256,
     maxCachedSessions: 100,
     _sessionCache: { map: [Object], list: [Object] } },
  socketPath: undefined,
  timeout: undefined,
  method: 'GET',
  path: '/1/thermostat?json=%7B%22selection%22%3A%7B%22selectionType%22%3A%22registered%22%2C%22selectionMatch%22%3A%22%22%2C%22includeSensors%22%3Atrue%7D%7D',
  _ended: false }
[11/8/2017, 6:47:03 PM] [Ecobee] { page: { page: 1, totalPages: 1, pageSize: 1, total: 1 },
  thermostatList: 
   [ { identifier: '511856934572',
       name: 'C Ecobee',
       thermostatRev: '171108232231',
       isRegistered: true,
       modelNumber: 'apolloSmart',
       brand: 'ecobee',
       features: 'HomeKit',
       lastModified: '2017-11-08 23:22:31',
       thermostatTime: '2017-11-08 18:47:03',
       utcTime: '2017-11-08 23:47:03',
       remoteSensors: [Object] } ],
  status: { code: 0, message: '' } }
[11/8/2017, 6:47:03 PM] [Ecobee] Update sensors
[11/8/2017, 6:47:03 PM] [Ecobee] Setting values of sensors...
[11/8/2017, 6:47:03 PM] [Ecobee] [Family Room] Updating sensor measurement...
[11/8/2017, 6:47:03 PM] [Ecobee] { id: 'rs:100',
  name: 'Family Room',
  type: 'ecobee3_remote_sensor',
  code: 'ZF32',
  inUse: true,
  capability: 
   [ { id: '1', type: 'temperature', value: '716' },
     { id: '2', type: 'occupancy', value: 'true' } ] }
[11/8/2017, 6:47:03 PM] [Ecobee] [Family Room] 22.0°C | Occupied
[11/8/2017, 6:47:03 PM] [Ecobee] [C Ecobee] Updating sensor measurement...
[11/8/2017, 6:47:03 PM] [Ecobee] { id: 'ei:0',
  name: 'C Ecobee',
  type: 'thermostat',
  inUse: false,
  capability: 
   [ { id: '1', type: 'temperature', value: '721' },
     { id: '2', type: 'humidity', value: '57' },
     { id: '3', type: 'occupancy', value: 'true' } ],
  code: '511856934572' }
[11/8/2017, 6:47:03 PM] [Ecobee] [C Ecobee] 22.3°C | 57% | Occupied
[11/8/2017, 6:47:03 PM] [Ecobee] Cleaning unused cached Homebridge accessories...
[11/8/2017, 6:47:03 PM] [Ecobee] {}
[11/8/2017, 6:47:03 PM] [Ecobee] Wait | 30 seconds
```
</details>

**Comment by Chiragbrains** [comment]
I sent you my Debug mode. BTW, I am trying to get Motion Sensing to increase or decrease the temp when it detects motion and when it does not detect motion, and it does not seem to work. Do you know if I can do this?

Thanks,
Chirag

**Comment by vojtamolda** [comment]
Thanks for the logs. I think I've got an idea what could be a problem now. What version of _Homebridge_ and the _homebridge-ecobee3-plugin_ are you using?

**Comment by Chiragbrains** [comment]
Homebridge: 0.4.3
homebridge-ecobee3-plugin: 0.1.4

**Comment by vojtamolda** [comment]
Thanks. I'll get the exact same versions and get back here with my findings.

**Comment by vojtamolda** [comment]
The problem is fixed. You can either get the latest version of this plugin (0.1.5) or _Homebridge_ server (>0.4.11) and the crash shouldn't be happening.

**Comment by Chiragbrains** [comment]
Thanks

**Comment by LaChrome** [comment]
@vojtamolda - It seems this issue is happening again with the latest version of Homebridge 0.4.45

I now get the same crash: “callback is not a function”
