### ISSUE TITLE
Add config.json sample to docs

### ISSUE THREAD

**Issue by johnschult** [vojtamolda/homebridge-ecobee3-sensors#8]
After successfully adding the app on ecobee.com, the following is logged and Homebridge restarts:

```
[12/8/2016, 7:30:17 PM] [homebridge-ecobee3-sensors.Ecobee 3 Sensors] Authorization successful :-)
[12/8/2016, 7:30:17 PM] [homebridge-ecobee3-sensors.Ecobee 3 Sensors] Update sensors
/usr/lib/node_modules/homebridge-ecobee3-sensors/source/platform.js:221
if ((this.config.exclude_thermostat === true) && (sensorConfig.type !== 'ecobee3_remote_sensor')) continue
^
TypeError: Cannot read property 'exclude_thermostat' of null
at EcobeePlatform.sensors (/usr/lib/node_modules/homebridge-ecobee3-sensors/source/platform.js:221:23)
at EcobeePlatform.<anonymous> (/usr/lib/node_modules/homebridge-ecobee3-sensors/source/platform.js:185:16)
at emitNone (events.js:91:20)
at IncomingMessage.emit (events.js:185:7)
at endReadableNT (_stream_readable.js:974:12)
at _combinedTickCallback (internal/process/next_tick.js:74:11)
at process._tickCallback (internal/process/next_tick.js:98:9)
homebridge.service: main process exited, code=exited, status=1/FAILURE
Unit homebridge.service entered failed state.
homebridge.service holdoff time over, scheduling restart.
Stopping Node.js HomeKit Server...
```

**Comment by johnschult** [comment]
My bad, I did not add the config...  you might want to add that to the README.

**Comment by vojtamolda** [comment]
Hello John,

Thanks for providing feedback on your experience while using the plugin. Please, bear with me, the plugin was released last week, so there are still some rough edges here and there.

If you don't mind, I'll re-open this issue. I think it's actually a good idea to add a sample of the configuration to the `readme.md`. I would just add the `platforms` section. I don't think it would be good to copy & paste the entire `config.json` file.
